{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-colourpicker
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/colourpicker_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/colourpicker/colourpicker_{{ version }}.tar.gz
  sha256: bc2c80eee046219038baef9f8f213c9824d7fec7f893f6a1b881dd44b4a8638a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-htmltools
    - r-htmlwidgets >=0.7
    - r-jsonlite
    - r-miniui >=0.1.1
    - r-shiny >=0.11.1
    - r-shinyjs >=2.0.0
  run:
    - r-base
    - r-ggplot2
    - r-htmltools
    - r-htmlwidgets >=0.7
    - r-jsonlite
    - r-miniui >=0.1.1
    - r-shiny >=0.11.1
    - r-shinyjs >=2.0.0

test:
  commands:
    - $R -e "library('colourpicker')"           # [not win]
    - "\"%R%\" -e \"library('colourpicker')\""  # [win]

about:
  home: https://github.com/daattali/colourpicker
  license: MIT
  summary: A colour picker that can be used as an input in Shiny apps or Rmarkdown documents. The colour picker supports alpha opacity, custom colour palettes, and many more options. A Plot Colour Helper tool is available as an RStudio Addin, which helps you pick colours to use in your plots. A more generic Colour Picker
    RStudio Addin is also provided to let  you select colours to use in your R code.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
