travis:
  secure:
    BINSTAR_TOKEN: Uh3BKzGn0IlxDVTespsRslFM1Z627+jskRK5VIndEhtz3XL9+4sabHA0F4XFfdUA77hegHbX55DjkZh2ni3tAvWXsvq/VfkjVw18e90orIgBfjwKWRb9wo1VDXJ86d8Q9E2/E9uv9VCvMbd5m2Vo4sTbK3CKro1NUF14yR1odRZEGQH0FOoy6chGeI+Mjcfyjr5RDDtlvw2m4yiRZT6dbh5umZ5oCNpyfnUvMEITr6Y3XCkq7ppw8KObZ6cNswAoayJbJjWz+HMKwVcEzEvQg/HrN2TruqJKaj4LXLcDaM8ZdFTtPe+jk5oDkFoLb9xGZ7SaM/IYCutUUhA2dehYqZQ0FDeUG2L1DfehUyfNe8H7GbluxPwbXiJ9SmnmGFM2E3cLwBxfMJCgjhBy6/nP9pCZG1qVAB7l9uD5PhGfuyuFXMrh4G7opiqDPp25ePD1wavj56nyHgPbif7FVMAqdSwfLqP8NqQnBCrgPBqalX/qs8vE/QcTyTehCI26Y/LtUg2CGhOsBCyTk0r+rbIM2C6PHH4hvwJJYWhZUYjb86lWWvFy2BBYLAOu6KkAda/22tsVxMp4MkyRacWw9Dto2Fis/0AjA2zv7z2N0qyAEotOI8KqiunS5AsdDCmDlF1bCRg2FdiR2Ga6Dl49eUM3dA3A91K95Q3SFBJzv2+ji9I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
