appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hH2pi6I0h/MF8LJkKuu9cpQq6jIs4h8DDdphftefb0FQUNz3bmeOlHwCz/5FloDX/cnCNAcSwdkP5nJN3nu615Xh6WcS8fY5tlaMBFg50lXF5GCpEkGpk5sAEJtkBxpHT2OEaTjzEf3nLqUd9Nus12J0X2/Sc/UU1dZMNTxBDTD0t4MMKOfIVKk5FwrcWaXPbuUmKbjRtA3iC03rhSxST0L9gVAHb/WU5H4x7AIKzFeZlMoBBmZ+j7OuUpAzT3zgfqe3ZDtnpiFAdwkDHKJZU64wqInIonu4FJaRShjYqDzvZasoreeWy8d6M8XpgzN8l8G6Cd1oOM4P/xwuCfaJ5vitzdqMbT5+sOlObdQrqAjFV9hGDY/VYuUWsPWMuRsTZ7rs3XeE4rIqXrrGUDOkB4aRNpSCpYECe+gAH3CcUaeisgVY0R5nIFqgCTO+rmQOcJ4LoGa6VKDmPXLDx+Fo+fmn7SCFVT3j/bkuJZ600nYctV6She6C5ofB8g/2UeVJA/W0ceGe7eGWmCLaWIdi+rT1B9NW4uunrC7ZoNDXzQHcI92x6P/1bSRgKlZG07Mv2sBmTDXU02sxESLv5TCHB/uChi9k3Ysc1hJ6C8dJAgq/zwRzHIurHyipXcSYFB5qzOrcn0eDJ952ZVFcs/K7pXlPAb2K4GEgTwzrsxpnlgI=}
